### ISSUE TITLE
Question: What key switches spawns?

### ISSUE THREAD

**Issue by peterjdev** [1blockyboi/OWWorkshopScripts#1]
Awesome custom game! People love it when I set it up.

Can't figure out how the switching spawns works though. It says INTERACT: TELEPORT TO ANOTHER SPAWN.

Anyway, love it, thank you!

**Comment by 1blockyboi** [comment]
Hi!

There is a special keybind that is called Interact. You see it used when teleporting through Symmetra's teleporter, destroying Torbjorn's turret, interacting with stuff in the PvE missions, etc. By default I think it is F, but I would recommend checking your control settings to see which keybind is assigned to Interact.

**Comment by peterjdev** [comment]
OH! Thank you so much!

I played for a few hours. Road Hog is my main. I've just left this map up in the background while watching YouTube. People absolutely love it.
